/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estado del proceso (público, sin base de datos) */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Identidad y roles (cualquier autenticado) */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Productos (VIEWER, ANALYST, PLANNER, ADMIN) */
        get: operations["list_products_api_v1_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle del producto con inventario y proveedores (los cuatro roles) */
        get: operations["get_product_api_v1_products__product_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Historia de consumo con estadísticos poblacionales (ANALYST, PLANNER, ADMIN) */
        get: operations["product_history_api_v1_products__product_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Serie primaria del producto (los cuatro roles) */
        get: operations["product_forecast_api_v1_products__product_id__forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{product_id}/recommendation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evaluación del producto en la ejecución, con cualquier outcome (los cuatro roles) */
        get: operations["product_recommendation_api_v1_products__product_id__recommendation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Posición de inventario del catálogo (los cuatro roles) */
        get: operations["list_inventory_api_v1_inventory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inventario del producto con sus líneas abiertas (los cuatro roles) */
        get: operations["get_inventory_api_v1_inventory__product_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/forecasts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Series primarias de la ejecución de forecast (los cuatro roles) */
        get: operations["list_forecasts_api_v1_forecasts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evaluaciones de la ejecución de recomendaciones (los cuatro roles) */
        get: operations["list_recommendations_api_v1_recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/{recommendation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Desglose completo de una evaluación (los cuatro roles) */
        get: operations["get_recommendation_api_v1_recommendations__recommendation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/{recommendation_id}/explanation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Explicación por plantilla de una evaluación (los cuatro roles) */
        get: operations["get_explanation_api_v1_recommendations__recommendation_id__explanation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ejecución de cálculo (PLANNER, ADMIN) */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CategoryRef */
        CategoryRef: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details: {
                [key: string]: unknown;
            } | unknown[];
            /** Correlation Id */
            correlation_id: string | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** ExplanationBody */
        ExplanationBody: {
            /** Generator */
            generator: string;
            /**
             * Status
             * @enum {string}
             */
            status: "VERIFIED" | "DEGRADED" | "NOT_APPLICABLE";
            /** Narrative */
            narrative: string | null;
            /** Warning */
            warning: "NARRATIVE_UNVERIFIED" | null;
        };
        /** ExplanationFact */
        ExplanationFact: {
            /** Key */
            key: string;
            /** Value */
            value: string;
            /** Display */
            display: string;
            /**
             * Unit
             * @enum {string}
             */
            unit: "QUANTITY" | "DAYS" | "FACTOR";
        };
        /** ForecastPage */
        ForecastPage: {
            /** Items */
            items: components["schemas"]["ForecastSeries"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            provenance: components["schemas"]["ForecastProvenance"];
        };
        /** ForecastPeriod */
        ForecastPeriod: {
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /** Predicted Quantity */
            predicted_quantity: string;
            /** Lower Bound */
            lower_bound: string;
            /** Upper Bound */
            upper_bound: string;
            /** Confidence Level */
            confidence_level: string;
            /** Method Used */
            method_used: string;
            /** Confidence Flag */
            confidence_flag: string;
        };
        /** ForecastProvenance */
        ForecastProvenance: {
            /** Data Origin */
            data_origin: string | null;
            /** Dataset Version */
            dataset_version: string;
            /** Generator Version */
            generator_version: string | null;
            /** Data Load Id */
            data_load_id: number;
            /**
             * As Of Date
             * Format: date
             */
            as_of_date: string;
            /** Run Id */
            run_id: number;
            /** Notices */
            notices: ("SYNTHETIC_DATA" | "V1_PROVISIONAL_POLICY")[];
            model_version: components["schemas"]["ModelRef"] | null;
        };
        /** ForecastSeries */
        ForecastSeries: {
            product: components["schemas"]["ProductRef"];
            model_version: components["schemas"]["ModelRef"];
            /** Periods */
            periods: components["schemas"]["ForecastPeriod"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** History */
        History: {
            /** Product Id */
            product_id: number;
            /**
             * Granularity
             * @enum {string}
             */
            granularity: "daily" | "weekly" | "monthly";
            /** Date From */
            date_from: string | null;
            /** Date To */
            date_to: string | null;
            /** Periods */
            periods: components["schemas"]["HistoryPeriod"][];
            statistics: components["schemas"]["HistoryStatistics"];
        };
        /** HistoryPeriod */
        HistoryPeriod: {
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /** Days */
            days: number;
            /** Days Observed */
            days_observed: number;
            /** Quantity */
            quantity: string;
            /** Stockout Days */
            stockout_days: number;
            /** Complete */
            complete: boolean;
        };
        /** HistoryStatistics */
        HistoryStatistics: {
            /** Periods Used */
            periods_used: number;
            /** Mean */
            mean: string | null;
            /** Std Dev */
            std_dev: string | null;
            /** Cv */
            cv: string | null;
            /** Zero Periods */
            zero_periods: number | null;
        };
        /** InventoryDetail */
        InventoryDetail: {
            /** Product Id */
            product_id: number;
            /** Sku */
            sku: string;
            /** On Hand */
            on_hand: string;
            /** Reserved */
            reserved: string;
            /** Available */
            available: string;
            /** In Transit Total */
            in_transit_total: string;
            /** Inventory Position Accounting */
            inventory_position_accounting: string;
            /** Last Movement At */
            last_movement_at: string | null;
            /** Data Origin */
            data_origin: string;
            /** Open Lines */
            open_lines: components["schemas"]["OpenLine"][];
        };
        /** InventoryItem */
        InventoryItem: {
            /** Product Id */
            product_id: number;
            /** Sku */
            sku: string;
            /** On Hand */
            on_hand: string;
            /** Reserved */
            reserved: string;
            /** Available */
            available: string;
            /** In Transit Total */
            in_transit_total: string;
            /** Inventory Position Accounting */
            inventory_position_accounting: string;
            /** Last Movement At */
            last_movement_at: string | null;
            /** Data Origin */
            data_origin: string;
        };
        /** InventoryPage */
        InventoryPage: {
            /** Items */
            items: components["schemas"]["InventoryItem"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Me */
        Me: {
            /** Subject Id */
            subject_id: string;
            /** Roles */
            roles: string[];
        };
        /** ModelRef */
        ModelRef: {
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
        /** OpenLine */
        OpenLine: {
            /** Order Number */
            order_number: string;
            supplier: components["schemas"]["SupplierRef"];
            /** Status */
            status: string;
            /**
             * Expected On
             * Format: date
             */
            expected_on: string;
            /** Quantity Pending */
            quantity_pending: string;
        };
        /** Product */
        Product: {
            /** Id */
            id: number;
            /** Sku */
            sku: string;
            /** Name */
            name: string;
            category: components["schemas"]["CategoryRef"];
            /** Unit Of Measure */
            unit_of_measure: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Valid From
             * Format: date
             */
            valid_from: string;
            /** Valid To */
            valid_to: string | null;
            /** Data Origin */
            data_origin: string;
        };
        /** ProductDetail */
        ProductDetail: {
            /** Id */
            id: number;
            /** Sku */
            sku: string;
            /** Name */
            name: string;
            category: components["schemas"]["CategoryRef"];
            /** Unit Of Measure */
            unit_of_measure: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Valid From
             * Format: date
             */
            valid_from: string;
            /** Valid To */
            valid_to: string | null;
            /** Data Origin */
            data_origin: string;
            inventory: components["schemas"]["ProductInventory"] | null;
            /** Suppliers */
            suppliers: components["schemas"]["ProductSupplier"][];
        };
        /** ProductForecast */
        ProductForecast: {
            product: components["schemas"]["ProductRef"];
            model_version: components["schemas"]["ModelRef"];
            /** Periods */
            periods: components["schemas"]["ForecastPeriod"][];
            provenance: components["schemas"]["ForecastProvenance"];
        };
        /** ProductInventory */
        ProductInventory: {
            /** On Hand */
            on_hand: string;
            /** Reserved */
            reserved: string;
            /** In Transit Total */
            in_transit_total: string;
            /** Last Movement At */
            last_movement_at: string | null;
        };
        /** ProductNamedRef */
        ProductNamedRef: {
            /** Id */
            id: number;
            /** Sku */
            sku: string;
            /** Name */
            name: string;
        };
        /** ProductPage */
        ProductPage: {
            /** Items */
            items: components["schemas"]["Product"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** ProductRef */
        ProductRef: {
            /** Id */
            id: number;
            /** Sku */
            sku: string;
        };
        /** ProductSupplier */
        ProductSupplier: {
            supplier: components["schemas"]["SupplierRef"];
            /** Moq */
            moq: string;
            /** Order Multiple */
            order_multiple: string;
            /** Unit Cost */
            unit_cost: string;
            /** Agreed Lead Time Days */
            agreed_lead_time_days: number;
            /** Is Preferred */
            is_preferred: boolean;
            /** Is Active */
            is_active: boolean;
        };
        /** ReasonDetail */
        ReasonDetail: {
            /** Code */
            code: string;
            /** Text */
            text: string;
        };
        /** RecommendationDetail */
        RecommendationDetail: {
            /** Id */
            id: number;
            /** Run Id */
            run_id: number;
            product: components["schemas"]["ProductNamedRef"];
            supplier: components["schemas"]["SupplierRef"] | null;
            /**
             * As Of Date
             * Format: date
             */
            as_of_date: string;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "RECOMMEND" | "NO_NEED" | "NOT_CALCULABLE";
            /** Reasons */
            reasons: string[];
            /** Flags */
            flags: string[];
            /** Missing Policy Parameters */
            missing_policy_parameters: string[];
            /** Forecast Id */
            forecast_id: number | null;
            /** Suggested Order Date */
            suggested_order_date: string | null;
            /** Recommended Quantity */
            recommended_quantity: string | null;
            /** Raw Quantity */
            raw_quantity: string | null;
            /** Reorder Point */
            reorder_point: string | null;
            /** Safety Stock */
            safety_stock: string | null;
            /** Lead Time Used Days */
            lead_time_used_days: number | null;
            /** Demand During Lead Time */
            demand_during_lead_time: string | null;
            /** Inventory Position At Calc */
            inventory_position_at_calc: string | null;
            /** Policy Set */
            policy_set: string;
            /** Policy Snapshot */
            policy_snapshot: {
                [key: string]: unknown;
            };
            /** Calculation Inputs */
            calculation_inputs: {
                [key: string]: unknown;
            };
            /** Engine Version */
            engine_version: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            provenance: components["schemas"]["RecommendationProvenance"];
        };
        /** RecommendationExplanation */
        RecommendationExplanation: {
            /** Recommendation Id */
            recommendation_id: number;
            /** Run Id */
            run_id: number;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "RECOMMEND" | "NO_NEED" | "NOT_CALCULABLE";
            explanation: components["schemas"]["ExplanationBody"];
            /** Facts */
            facts: components["schemas"]["ExplanationFact"][];
            /** Flags */
            flags: string[];
            /** Reasons */
            reasons: string[];
            /** Reason Details */
            reason_details: components["schemas"]["ReasonDetail"][];
            /** Missing Policy Parameters */
            missing_policy_parameters: string[];
            provenance: components["schemas"]["RecommendationProvenance"];
        };
        /** RecommendationItem */
        RecommendationItem: {
            /** Id */
            id: number;
            product: components["schemas"]["ProductNamedRef"];
            supplier: components["schemas"]["SupplierRef"] | null;
            /** Recommended Quantity */
            recommended_quantity: string | null;
            /** Raw Quantity */
            raw_quantity: string | null;
            /** Suggested Order Date */
            suggested_order_date: string | null;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "RECOMMEND" | "NO_NEED" | "NOT_CALCULABLE";
            /** Flags */
            flags: string[];
        };
        /** RecommendationPage */
        RecommendationPage: {
            /** Items */
            items: components["schemas"]["RecommendationItem"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            provenance: components["schemas"]["RecommendationProvenance"];
        };
        /** RecommendationProvenance */
        RecommendationProvenance: {
            /** Data Origin */
            data_origin: string | null;
            /** Dataset Version */
            dataset_version: string;
            /** Generator Version */
            generator_version: string | null;
            /** Data Load Id */
            data_load_id: number;
            /**
             * As Of Date
             * Format: date
             */
            as_of_date: string;
            /** Run Id */
            run_id: number;
            /** Notices */
            notices: ("SYNTHETIC_DATA" | "V1_PROVISIONAL_POLICY")[];
            /** Engine Version */
            engine_version: string | null;
            /** Policy Set */
            policy_set: string | null;
            /** Forecast Run Id */
            forecast_run_id: number | null;
        };
        /** RunDataLoad */
        RunDataLoad: {
            /** Id */
            id: number;
            /** Dataset Version */
            dataset_version: string;
            /** Generator Version */
            generator_version: string | null;
            /** Data Origin */
            data_origin: string | null;
        };
        /** RunDetail */
        RunDetail: {
            /** Id */
            id: number;
            /**
             * Run Type
             * @enum {string}
             */
            run_type: "FORECAST" | "RECOMMENDATION";
            /**
             * Status
             * @enum {string}
             */
            status: "COMPLETED" | "FAILED";
            /**
             * As Of Date
             * Format: date
             */
            as_of_date: string;
            data_load: components["schemas"]["RunDataLoad"];
            versions: components["schemas"]["RunVersions"];
            /** Counts */
            counts: {
                [key: string]: unknown;
            };
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Finished At
             * Format: date-time
             */
            finished_at: string;
            /** Error */
            error: {
                [key: string]: unknown;
            } | null;
        };
        /** RunVersions */
        RunVersions: {
            /** Engine Version */
            engine_version: string | null;
            /** Forecast Run Id */
            forecast_run_id: number | null;
            reference_model_version: components["schemas"]["ModelRef"] | null;
            /** Config Sha256 */
            config_sha256: string;
        };
        /** SupplierRef */
        SupplierRef: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name */
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_products_api_v1_products_get: {
        parameters: {
            query?: {
                /** @description Subcadena en sku o nombre */
                search?: string | null;
                category_id?: number | null;
                is_active?: boolean | null;
                /** @description sku | name | id, con - para descendente; por defecto sku */
                sort?: string | null;
                /** @description Página, desde 1 */
                page?: number;
                /** @description Tamaño de página (1–200) */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductPage"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_product_api_v1_products__product_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetail"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    product_history_api_v1_products__product_id__history_get: {
        parameters: {
            query?: {
                /** @description Inclusivo; por defecto, primer día con consumo */
                date_from?: string | null;
                /** @description Inclusivo; por defecto, último día con consumo */
                date_to?: string | null;
                granularity?: "daily" | "weekly" | "monthly";
            };
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["History"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    product_forecast_api_v1_products__product_id__forecast_get: {
        parameters: {
            query?: {
                run_id?: number | null;
            };
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductForecast"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    product_recommendation_api_v1_products__product_id__recommendation_get: {
        parameters: {
            query?: {
                run_id?: number | null;
            };
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationDetail"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_inventory_api_v1_inventory_get: {
        parameters: {
            query?: {
                product_id?: number | null;
                category_id?: number | null;
                /** @description sku | on_hand | available, con - para descendente; por defecto sku */
                sort?: string | null;
                /** @description Página, desde 1 */
                page?: number;
                /** @description Tamaño de página (1–200) */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryPage"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_inventory_api_v1_inventory__product_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryDetail"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_forecasts_api_v1_forecasts_get: {
        parameters: {
            query?: {
                product_id?: number | null;
                category_id?: number | null;
                /** @description Por defecto, la regla determinista de DT-066 */
                run_id?: number | null;
                /** @description Página, desde 1 */
                page?: number;
                /** @description Tamaño de página (1–200) */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastPage"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_recommendations_api_v1_recommendations_get: {
        parameters: {
            query?: {
                outcome?: "RECOMMEND" | "NO_NEED" | "NOT_CALCULABLE";
                product_id?: number | null;
                category_id?: number | null;
                supplier_id?: number | null;
                /** @description Por defecto, la regla determinista de DT-066 */
                run_id?: number | null;
                /** @description sku | recommended_quantity | suggested_order_date; por defecto sku */
                sort?: string | null;
                /** @description Página, desde 1 */
                page?: number;
                /** @description Tamaño de página (1–200) */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationPage"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_recommendation_api_v1_recommendations__recommendation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recommendation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationDetail"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_explanation_api_v1_recommendations__recommendation_id__explanation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recommendation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationExplanation"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
