-- 0002 — Tablas del forecast de U3: model_versions, calculation_runs y forecasts (DT-057, docs/04 §9.10).
--
-- Los baselines no se entrenan ni se evalúan: en sus filas de model_versions, los campos de
-- entrenamiento, métricas y status son NULL (DT-057). Una ejecución de forecast persiste las series de
-- los tres baselines; is_primary marca la que consumirá U4. Ejecuciones y forecasts son inmutables.

CREATE TABLE model_versions (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               text        NOT NULL,
    version            text        NOT NULL,
    algorithm          text        NOT NULL,
    trained_at         timestamptz,
    training_data_from date,
    training_data_to   date,
    metrics            jsonb,
    baseline_metrics   jsonb,
    hyperparameters    jsonb       NOT NULL,
    status             text CHECK (status IN ('TRAINING', 'EVALUATED', 'PRODUCTION', 'ARCHIVED', 'REJECTED')),
    external_ref       text,
    is_baseline        boolean     NOT NULL,
    created_at         timestamptz NOT NULL DEFAULT transaction_timestamp(),
    CONSTRAINT model_versions_name_version_uk UNIQUE (name, version),
    -- El ciclo de vida de docs/05 §13 es el de «cada modelo entrenado»; un baseline no lo tiene.
    CONSTRAINT model_versions_baseline_status_ck CHECK (is_baseline = (status IS NULL)),
    CONSTRAINT model_versions_training_window_ck
        CHECK (training_data_from IS NULL OR training_data_to IS NULL OR training_data_from <= training_data_to)
);

-- Solo COMPLETED o FAILED: cada ejecución se escribe una vez, en su estado final.
CREATE TABLE calculation_runs (
    id                         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_type                   text        NOT NULL CHECK (run_type IN ('FORECAST', 'RECOMMENDATION')),
    status                     text        NOT NULL CHECK (status IN ('COMPLETED', 'FAILED')),
    as_of_date                 date        NOT NULL,
    data_load_id               bigint      NOT NULL REFERENCES data_loads (id),
    reference_model_version_id bigint      REFERENCES model_versions (id),
    config_sha256              text        NOT NULL CHECK (config_sha256 ~ '^[0-9a-f]{64}$'),
    summary                    jsonb       NOT NULL,
    error                      jsonb,
    started_at                 timestamptz NOT NULL,
    finished_at                timestamptz NOT NULL,
    CONSTRAINT calculation_runs_forecast_reference_ck
        CHECK (run_type <> 'FORECAST' OR reference_model_version_id IS NOT NULL),
    CONSTRAINT calculation_runs_error_ck CHECK ((status = 'FAILED') = (error IS NOT NULL)),
    CONSTRAINT calculation_runs_times_ck CHECK (started_at <= finished_at)
);

-- Idempotencia (C8): como máximo una ejecución COMPLETED por configuración, corte y carga.
CREATE UNIQUE INDEX calculation_runs_completed_ux
    ON calculation_runs (run_type, as_of_date, data_load_id, config_sha256)
    WHERE status = 'COMPLETED';

CREATE TABLE forecasts (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calculation_run_id bigint      NOT NULL REFERENCES calculation_runs (id),
    product_id         bigint      NOT NULL REFERENCES products (id),
    location_id        bigint      NOT NULL REFERENCES locations (id),
    model_version_id   bigint      NOT NULL REFERENCES model_versions (id),
    as_of_date         date        NOT NULL,
    generated_at       timestamptz NOT NULL DEFAULT transaction_timestamp(),
    period_start       date        NOT NULL,
    period_end         date        NOT NULL,
    granularity        text        NOT NULL CHECK (granularity IN ('DAILY', 'WEEKLY', 'MONTHLY')),
    predicted_quantity numeric     NOT NULL,
    lower_bound        numeric     NOT NULL,
    upper_bound        numeric     NOT NULL,
    confidence_level   numeric     NOT NULL CHECK (confidence_level > 0 AND confidence_level < 1),
    method_used        text        NOT NULL CHECK (method_used IN ('MODEL', 'BASELINE', 'INTERMITTENT_METHOD')),
    confidence_flag    text        NOT NULL CHECK (confidence_flag IN ('STANDARD', 'INSUFFICIENT_HISTORY')),
    is_primary         boolean     NOT NULL,
    CONSTRAINT forecasts_after_cut_ck CHECK (period_start > as_of_date),
    CONSTRAINT forecasts_weekly_period_ck CHECK (granularity <> 'WEEKLY' OR period_end = period_start + 7),
    CONSTRAINT forecasts_interval_ck
        CHECK (0 <= lower_bound AND lower_bound <= predicted_quantity AND predicted_quantity <= upper_bound),
    CONSTRAINT forecasts_scale_ck
        CHECK (scale(predicted_quantity) <= 6 AND scale(lower_bound) <= 6 AND scale(upper_bound) <= 6),
    CONSTRAINT forecasts_run_series_period_uk
        UNIQUE (calculation_run_id, model_version_id, product_id, location_id, period_start)
);

-- Una sola serie primaria por producto, ubicación y semana en cada ejecución (C9).
CREATE UNIQUE INDEX forecasts_primary_ux
    ON forecasts (calculation_run_id, product_id, location_id, period_start)
    WHERE is_primary;

-- Inmutabilidad: una ejecución y sus forecasts no se modifican ni se borran (DT-057).
CREATE FUNCTION reject_immutable_change() RETURNS trigger
    LANGUAGE plpgsql AS
$$
BEGIN
    RAISE EXCEPTION '% is immutable: % rejected', TG_TABLE_NAME, TG_OP;
END;
$$;

CREATE TRIGGER calculation_runs_immutable
    BEFORE UPDATE OR DELETE ON calculation_runs
    FOR EACH ROW EXECUTE FUNCTION reject_immutable_change();

CREATE TRIGGER forecasts_immutable
    BEFORE UPDATE OR DELETE ON forecasts
    FOR EACH ROW EXECUTE FUNCTION reject_immutable_change();
