-- 0003 — Ejecución de recomendaciones de U4: columnas de calculation_runs y tabla recommendations
-- (DT-059 a DT-062, docs/04 §9.11).
--
-- Una fila inmutable por evaluación (RECOMMEND, NO_NEED o NOT_CALCULABLE); un fallo de la ejecución es
-- calculation_runs.status = 'FAILED' y no deja recomendaciones. Sin status, resolved_*, urgency ni
-- data_origin (DT-059). Añadir columnas nulables no reescribe filas ni dispara el trigger de inmutabilidad.

ALTER TABLE calculation_runs
    ADD COLUMN forecast_run_id bigint REFERENCES calculation_runs (id),
    ADD COLUMN engine_version  text,
    -- La ejecución de forecast consumida (DT-061) y la versión del motor (DT-062): solo en RECOMMENDATION.
    ADD CONSTRAINT calculation_runs_forecast_run_ck
        CHECK ((run_type = 'RECOMMENDATION') = (forecast_run_id IS NOT NULL)),
    ADD CONSTRAINT calculation_runs_engine_version_ck
        CHECK ((run_type = 'RECOMMENDATION') = (engine_version IS NOT NULL)),
    ADD CONSTRAINT calculation_runs_engine_version_format_ck
        CHECK (engine_version ~ '^[0-9]+\.[0-9]+\.[0-9]+$'),
    ADD CONSTRAINT calculation_runs_recommendation_reference_ck
        CHECK (run_type <> 'RECOMMENDATION' OR reference_model_version_id IS NULL);

CREATE TABLE recommendations (
    id                         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    calculation_run_id         bigint      NOT NULL REFERENCES calculation_runs (id),
    product_id                 bigint      NOT NULL REFERENCES products (id),
    location_id                bigint      NOT NULL REFERENCES locations (id),
    as_of_date                 date        NOT NULL,
    outcome                    text        NOT NULL CHECK (outcome IN ('RECOMMEND', 'NO_NEED', 'NOT_CALCULABLE')),
    reasons                    text[]      NOT NULL,
    flags                      text[]      NOT NULL,
    missing_policy_parameters  text[]      NOT NULL,
    forecast_id                bigint      REFERENCES forecasts (id),
    suggested_supplier_id      bigint      REFERENCES suppliers (id),
    suggested_order_date       date,
    recommended_quantity       numeric,
    raw_quantity               numeric,
    reorder_point              numeric,
    safety_stock               numeric,
    lead_time_used_days        integer,
    demand_during_lead_time    numeric,
    inventory_position_at_calc numeric,
    policy_set                 text        NOT NULL CHECK (policy_set = 'V1_PROVISIONAL'),
    policy_snapshot            jsonb       NOT NULL,
    calculation_inputs         jsonb       NOT NULL,
    engine_version             text        NOT NULL CHECK (engine_version ~ '^[0-9]+\.[0-9]+\.[0-9]+$'),
    generated_at               timestamptz NOT NULL DEFAULT transaction_timestamp(),
    CONSTRAINT recommendations_run_product_location_uk UNIQUE (calculation_run_id, product_id, location_id),
    -- Vocabularios cerrados de U1 (docs/06 §16.5).
    CONSTRAINT recommendations_reasons_vocabulary_ck CHECK (reasons <@ ARRAY[
        'PRODUCT_INACTIVE', 'PRODUCT_OUT_OF_VALIDITY', 'NO_ACTIVE_PREFERRED_SUPPLIER', 'NEGATIVE_ON_HAND',
        'FORECAST_MISSING', 'FORECAST_TOO_SHORT', 'INSUFFICIENT_HISTORY', 'MISSING_POLICY_PARAMETER']::text[]),
    CONSTRAINT recommendations_flags_vocabulary_ck CHECK (flags <@ ARRAY[
        'LEAD_TIME_AGREED_FALLBACK', 'LEAD_TIME_CAPPED', 'MOQ_APPLIED', 'ORDER_MULTIPLE_ROUNDING',
        'UNCOUNTED_TRANSIT', 'OVERDUE_ORDERS_EXCLUDED', 'ZERO_FORECAST_DEMAND']::text[]),
    CONSTRAINT recommendations_missing_parameters_vocabulary_ck
        CHECK (missing_policy_parameters <@ ARRAY['R', 'z', 'N', 'N_MIN', 'LT_MAX']::text[]),
    -- Invariantes por outcome (DT-051, DT-053, DT-059).
    CONSTRAINT recommendations_reasons_ck
        CHECK ((outcome = 'NOT_CALCULABLE') = (cardinality(reasons) > 0)),
    CONSTRAINT recommendations_missing_parameters_ck
        CHECK ((cardinality(missing_policy_parameters) > 0) = ('MISSING_POLICY_PARAMETER' = ANY (reasons))),
    CONSTRAINT recommendations_forecast_ck
        CHECK ((forecast_id IS NULL) = ('FORECAST_MISSING' = ANY (reasons))),
    CONSTRAINT recommendations_order_date_ck
        CHECK ((outcome = 'RECOMMEND') = (suggested_order_date IS NOT NULL)
               AND (suggested_order_date IS NULL OR suggested_order_date = as_of_date)),
    CONSTRAINT recommendations_quantity_ck
        CHECK ((outcome = 'RECOMMEND') = (recommended_quantity IS NOT NULL)
               AND (recommended_quantity IS NULL OR recommended_quantity > 0)),
    CONSTRAINT recommendations_raw_quantity_ck CHECK (CASE outcome
        WHEN 'RECOMMEND' THEN coalesce(raw_quantity > 0, false)
        WHEN 'NO_NEED' THEN coalesce(raw_quantity = 0, false)
        ELSE raw_quantity IS NULL END),
    CONSTRAINT recommendations_supplier_flags_ck
        CHECK (outcome = 'RECOMMEND' OR NOT (flags && ARRAY['MOQ_APPLIED', 'ORDER_MULTIPLE_ROUNDING']::text[]))
);

-- Inmutabilidad (DT-059): una evaluación no se modifica ni se borra.
CREATE TRIGGER recommendations_immutable
    BEFORE UPDATE OR DELETE ON recommendations
    FOR EACH ROW EXECUTE FUNCTION reject_immutable_change();
